services:
  - type: web
    name: live-fullstack-frontend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install --include=dev && npm run build:h5
    startCommand: cd frontend && npm start
    envVars:
      - key: USE_MOCK
        value: "true"
    autoDeploy: true
